[package]
name = "hello_macro_drive"
version = "0.1.0"
authors = ["mrtan <freemrtan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = "0.15.43"
quote = "0.6.13"